from django.urls import path

from .views_documento import (
    DocumentoListView,
    DocumentoCreateView,
    DocumentoDetailView,
    DocumentoUpdateView,
    documento_delete_view,
    documento_download_view,
)
from .views_risco import (
    RiscoListView,
    RiscoCreateView,
    RiscoDetailView,
    RiscoUpdateView,
    risco_delete_view,
    risco_dashboard_view,
)
from .views_planejamento import (
    MapaCorrespondenciaListView,
    PlanoFisicoListView,
    PlanoFisicoCreateView,
    PlanoFisicoDetailView,
    PlanoFisicoUpdateView,
    PlanoFisicoItemUpdateView,
    PlanoFisicoDashboardView,
    gerar_curva_s_ajax,
    plano_fisico_delete_view,
    criar_baseline_view,
    sugerir_mapeamento_ajax,
    vincular_mapeamento_ajax,
)
from .views_qualidade import (
    NaoConformidadeCreateView,
    NaoConformidadeDetailView,
    NaoConformidadeListView,
    NaoConformidadeUpdateView,
    nao_conformidade_export_view,
    nao_conformidade_pdf_view,
    nao_conformidade_aprovacao_pdf_view,
    nao_conformidade_aprovacao_excel_view,
)
from .views_aquisicoes import (
    CotacaoCreateView,
    CotacaoDetailView,
    CotacaoListView,
    FornecedorCreateView,
    FornecedorListView,
    OrdemCompraDetailView,
    OrdemCompraListView,
    SolicitacaoCompraCreateView,
    SolicitacaoCompraDetailView,
    SolicitacaoCompraListView,
    cotacao_pdf_view,
    solicitacao_compra_pdf_view,
    solicitacao_compra_export_view,
    solicitacao_compra_lista_pdf_view,
    cotacao_export_view,
    cotacao_lista_pdf_view,
)
from .views_usuarios import SistemaAdminView, UsuarioEmpresaCreateView, UsuarioEmpresaListView
from .auth_mixins import ConstrutaskLoginView, ConstrutaskLogoutView
from .views_lgpd import LgpdGovernancaView, PoliticaPrivacidadeView, TermosUsoView, lgpd_governanca_pdf_view
from .views_jobs import (
    JobAssincronoListView,
    plano_contas_importar_job_view,
    relatorio_financeiro_job_view,
    sincronizar_alertas_job_view,
)
from .views_alertas import (
    AlertaOperacionalDetailView,
    CentralAlertasOperacionaisView,
    PainelExecutivoAlertasView,
    alerta_operacional_dashboard_export_view,
    alerta_operacional_dashboard_pdf_view,
    alerta_operacional_workflow_view,
)
from .views_financeiro import (
    FechamentoMensalView,
    ProjecaoFinanceiraView,
    fechamento_mensal_export_view,
    fechamento_mensal_pdf_view,
    projecao_financeira_export_view,
    projecao_financeira_pdf_view,
)
from .views_observabilidade import ObservabilidadeDashboardView, observabilidade_teste_erro_view
from .views_operacao import OperacaoTecnicaDashboardView
from .views_comunicacoes import (
    ReuniaoComunicacaoCreateView,
    ReuniaoComunicacaoDetailView,
    ReuniaoComunicacaoListView,
    reuniao_comunicacao_ata_excel_view,
    reuniao_comunicacao_ata_pdf_view,
    reuniao_comunicacao_compilar_ata_view,
    reuniao_comunicacao_pauta_excel_view,
    reuniao_comunicacao_pauta_pdf_view,
)
from .views import (
    CompromissoCreateView,
    ContratoDetailView,
    AditivoContratoCreateView,
    aditivo_contrato_workflow_view,
    compromisso_delete_view,
    compromisso_export_view,
    compromisso_lista_pdf_view,
    compromisso_aprovacao_pdf_view,
    compromisso_aprovacao_excel_view,
    compromisso_pdf_view,
    CompromissoListView,
    CompromissoUpdateView,
    CurvaABCView,
    curva_abc_export_view,
    curva_abc_pdf_view,
    CentralEvidenciasView,
    DossieObraView,
    dossie_obra_pdf_view,
    HomeView,
    ModuloGrupoView,
    MedicaoCreateView,
    medicao_aprovacao_pdf_view,
    medicao_aprovacao_excel_view,
    medicao_delete_view,
    MedicaoDetailView,
    medicao_export_view,
    medicao_lista_pdf_view,
    MedicaoListView,
    MedicaoUpdateView,
    NotaFiscalCreateView,
    nota_fiscal_delete_view,
    nota_fiscal_export_view,
    nota_fiscal_lista_pdf_view,
    nota_fiscal_dados_view,
    NotaFiscalListView,
    NotaFiscalUpdateView,
    ObraCreateView,
    ObraListView,
    ObraUpdateView,
    PlanoContasConsultaView,
    PlanoContasUpdateView,
    contrato_dados_view,
    medicao_dados_view,
    plano_contas_delete_view,
    plano_contas_criar_baseline_view,
    plano_contas_baseline_workflow_view,
    plano_contas_baseline_aprovacao_pdf_view,
    plano_contas_baseline_aprovacao_excel_view,
    plano_contas_export_view,
    plano_contas_notas_view,
    selecionar_obra_contexto_view,
)


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("modulos/<slug:slug>/", ModuloGrupoView.as_view(), name="modulo_grupo"),
    path("alertas-operacionais/", CentralAlertasOperacionaisView.as_view(), name="alerta_operacional_list"),
    path("alertas-operacionais/dashboard/", PainelExecutivoAlertasView.as_view(), name="alerta_operacional_dashboard"),
    path("alertas-operacionais/dashboard/exportar/", alerta_operacional_dashboard_export_view, name="alerta_operacional_dashboard_export"),
    path("alertas-operacionais/dashboard/pdf/", alerta_operacional_dashboard_pdf_view, name="alerta_operacional_dashboard_pdf"),
    path("alertas-operacionais/sincronizar/", sincronizar_alertas_job_view, name="alerta_operacional_sincronizar_job"),
    path("alertas-operacionais/<int:pk>/", AlertaOperacionalDetailView.as_view(), name="alerta_operacional_detail"),
    path("alertas-operacionais/<int:pk>/workflow/", alerta_operacional_workflow_view, name="alerta_operacional_workflow"),
    path("jobs/", JobAssincronoListView.as_view(), name="jobs_assincronos"),
    path("observabilidade/", ObservabilidadeDashboardView.as_view(), name="observabilidade_dashboard"),
    path("observabilidade/teste-erro/", observabilidade_teste_erro_view, name="observabilidade_teste_erro"),
    path("operacao-tecnica/", OperacaoTecnicaDashboardView.as_view(), name="operacao_tecnica_dashboard"),
    path("comunicacoes/", ReuniaoComunicacaoListView.as_view(), name="reuniao_comunicacao_list"),
    path("comunicacoes/nova/", ReuniaoComunicacaoCreateView.as_view(), name="reuniao_comunicacao_create"),
    path("comunicacoes/<int:pk>/", ReuniaoComunicacaoDetailView.as_view(), name="reuniao_comunicacao_detail"),
    path("comunicacoes/<int:pk>/compilar-ata/", reuniao_comunicacao_compilar_ata_view, name="reuniao_comunicacao_compilar_ata"),
    path("comunicacoes/<int:pk>/pauta/excel/", reuniao_comunicacao_pauta_excel_view, name="reuniao_comunicacao_pauta_excel"),
    path("comunicacoes/<int:pk>/pauta/pdf/", reuniao_comunicacao_pauta_pdf_view, name="reuniao_comunicacao_pauta_pdf"),
    path("comunicacoes/<int:pk>/ata/excel/", reuniao_comunicacao_ata_excel_view, name="reuniao_comunicacao_ata_excel"),
    path("comunicacoes/<int:pk>/ata/pdf/", reuniao_comunicacao_ata_pdf_view, name="reuniao_comunicacao_ata_pdf"),
    path("obras/", ObraListView.as_view(), name="obra_list"),
    path("obras/nova/", ObraCreateView.as_view(), name="obra_create"),
    path("obras/<int:pk>/editar/", ObraUpdateView.as_view(), name="obra_update"),
    path("contexto-obra/", selecionar_obra_contexto_view, name="selecionar_obra_contexto"),
    path("fechamento-mensal/", FechamentoMensalView.as_view(), name="fechamento_mensal"),
    path("fechamento-mensal/exportar/", fechamento_mensal_export_view, name="fechamento_mensal_export"),
    path("fechamento-mensal/pdf/", fechamento_mensal_pdf_view, name="fechamento_mensal_pdf"),
    path("fechamento-mensal/enfileirar-relatorio/", relatorio_financeiro_job_view, {"relatorio": "fechamento"}, name="fechamento_mensal_job"),
    path("projecao-financeira/", ProjecaoFinanceiraView.as_view(), name="projecao_financeira"),
    path("projecao-financeira/exportar/", projecao_financeira_export_view, name="projecao_financeira_export"),
    path("projecao-financeira/pdf/", projecao_financeira_pdf_view, name="projecao_financeira_pdf"),
    path("projecao-financeira/enfileirar-relatorio/", relatorio_financeiro_job_view, {"relatorio": "projecao"}, name="projecao_financeira_job"),
    path("curva-abc/", CurvaABCView.as_view(), name="curva_abc"),
    path("curva-abc/exportar/", curva_abc_export_view, name="curva_abc_export"),
    path("curva-abc/pdf/", curva_abc_pdf_view, name="curva_abc_pdf"),
    path("central-evidencias/", CentralEvidenciasView.as_view(), name="central_evidencias"),
    path("relatorios/dossie-obra/", DossieObraView.as_view(), name="dossie_obra"),
    path("relatorios/dossie-obra/pdf/", dossie_obra_pdf_view, name="dossie_obra_pdf"),
    path("plano-de-contas/", PlanoContasConsultaView.as_view(), name="plano_contas_list"),
    path("plano-de-contas/exportar/", plano_contas_export_view, name="plano_contas_export"),
    path("plano-de-contas/baseline/", plano_contas_criar_baseline_view, name="plano_contas_criar_baseline"),
    path("plano-de-contas/baseline/<int:pk>/workflow/", plano_contas_baseline_workflow_view, name="plano_contas_baseline_workflow"),
    path("plano-de-contas/baseline/<int:pk>/aprovacao-pdf/", plano_contas_baseline_aprovacao_pdf_view, name="plano_contas_baseline_aprovacao_pdf"),
    path("plano-de-contas/baseline/<int:pk>/aprovacao-excel/", plano_contas_baseline_aprovacao_excel_view, name="plano_contas_baseline_aprovacao_excel"),
    path("plano-de-contas/<int:pk>/editar/", PlanoContasUpdateView.as_view(), name="plano_contas_update"),
    path("plano-de-contas/excluir/", plano_contas_delete_view, name="plano_contas_delete"),
    path("plano-de-contas/<int:pk>/notas/", plano_contas_notas_view, name="plano_contas_notas"),
    path("plano-de-contas/importar/", plano_contas_importar_job_view, name="plano_contas_importar"),
    path("compras-contratacoes/", CompromissoListView.as_view(), name="compromisso_list"),
    path("compras-contratacoes/exportar/", compromisso_export_view, name="compromisso_export"),
    path("compras-contratacoes/pdf/", compromisso_lista_pdf_view, name="compromisso_lista_pdf"),
    path("compras-contratacoes/nova/", CompromissoCreateView.as_view(), name="compromisso_create"),
    path("compras-contratacoes/<int:pk>/", ContratoDetailView.as_view(), name="contrato_detail"),
    path("compras-contratacoes/<int:pk>/pdf/", compromisso_pdf_view, name="compromisso_pdf"),
    path("compras-contratacoes/<int:pk>/aprovacao-pdf/", compromisso_aprovacao_pdf_view, name="compromisso_aprovacao_pdf"),
    path("compras-contratacoes/<int:pk>/aprovacao-excel/", compromisso_aprovacao_excel_view, name="compromisso_aprovacao_excel"),
    path("compras-contratacoes/<int:pk>/aditivos/nova/", AditivoContratoCreateView.as_view(), name="aditivo_contrato_create"),
    path("compras-contratacoes/aditivos/<int:pk>/workflow/", aditivo_contrato_workflow_view, name="aditivo_contrato_workflow"),
    path("compras-contratacoes/<int:pk>/editar/", CompromissoUpdateView.as_view(), name="compromisso_update"),
    path("compras-contratacoes/excluir/", compromisso_delete_view, name="compromisso_delete"),
    path("medicoes/", MedicaoListView.as_view(), name="medicao_list"),
    path("medicoes/exportar/", medicao_export_view, name="medicao_export"),
    path("medicoes/pdf/", medicao_lista_pdf_view, name="medicao_lista_pdf"),
    path("medicoes/nova/", MedicaoCreateView.as_view(), name="medicao_create"),
    path("medicoes/<int:pk>/", MedicaoDetailView.as_view(), name="medicao_detail"),
    path("medicoes/<int:pk>/aprovacao-pdf/", medicao_aprovacao_pdf_view, name="medicao_aprovacao_pdf"),
    path("medicoes/<int:pk>/aprovacao-excel/", medicao_aprovacao_excel_view, name="medicao_aprovacao_excel"),
    path("medicoes/<int:pk>/editar/", MedicaoUpdateView.as_view(), name="medicao_update"),
    path("medicoes/excluir/", medicao_delete_view, name="medicao_delete"),
    path("contratos/<int:pk>/dados/", contrato_dados_view, name="contrato_dados"),
    path("medicoes/<int:pk>/dados/", medicao_dados_view, name="medicao_dados"),
    path("notas-fiscais/", NotaFiscalListView.as_view(), name="nota_fiscal_list"),
    path("notas-fiscais/exportar/", nota_fiscal_export_view, name="nota_fiscal_export"),
    path("notas-fiscais/pdf/", nota_fiscal_lista_pdf_view, name="nota_fiscal_lista_pdf"),
    path("notas-fiscais/nova/", NotaFiscalCreateView.as_view(), name="nota_fiscal_create"),
    path("notas-fiscais/<int:pk>/editar/", NotaFiscalUpdateView.as_view(), name="nota_fiscal_update"),
    path("notas-fiscais/excluir/", nota_fiscal_delete_view, name="nota_fiscal_delete"),
    path("notas-fiscais/<int:pk>/dados/", nota_fiscal_dados_view, name="nota_fiscal_dados"),
    
    # Auth URLs
    path("accounts/login/", ConstrutaskLoginView.as_view(), name="login"),
    path("accounts/logout/", ConstrutaskLogoutView.as_view(), name="logout"),
    
    # UsuarioEmpresa URLs
    path("sistema-admin/", SistemaAdminView.as_view(), name="sistema_admin"),
    path("empresa-admin/", UsuarioEmpresaListView.as_view(), name="empresa_admin"),
    path("governanca/lgpd/", LgpdGovernancaView.as_view(), name="lgpd_governanca"),
    path("governanca/lgpd/pdf/", lgpd_governanca_pdf_view, name="lgpd_governanca_pdf"),
    path("politica-privacidade/", PoliticaPrivacidadeView.as_view(), name="politica_privacidade"),
    path("termos-uso/", TermosUsoView.as_view(), name="termos_uso"),
    
    # ISO 7.5 - Controle Documental
    path("documentos/", DocumentoListView.as_view(), name="documento_list"),
    path("documentos/novo/", DocumentoCreateView.as_view(), name="documento_create"),
    path("documentos/<int:pk>/", DocumentoDetailView.as_view(), name="documento_detail"),
    path("documentos/<int:pk>/editar/", DocumentoUpdateView.as_view(), name="documento_update"),
    path("documentos/<int:pk>/excluir/", documento_delete_view, name="documento_delete"),
    path("documentos/<int:pk>/download/", documento_download_view, name="documento_download"),
    path("documentos/<int:pk>/download/<int:revisao_pk>/", documento_download_view, name="documento_download_revisao"),

    # ISO 10 - Qualidade Operacional
    path("nao-conformidades/", NaoConformidadeListView.as_view(), name="nao_conformidade_list"),
    path("nao-conformidades/exportar/", nao_conformidade_export_view, name="nao_conformidade_export"),
    path("nao-conformidades/pdf/", nao_conformidade_pdf_view, name="nao_conformidade_pdf"),
    path("nao-conformidades/nova/", NaoConformidadeCreateView.as_view(), name="nao_conformidade_create"),
    path("nao-conformidades/<int:pk>/", NaoConformidadeDetailView.as_view(), name="nao_conformidade_detail"),
    path("nao-conformidades/<int:pk>/editar/", NaoConformidadeUpdateView.as_view(), name="nao_conformidade_update"),
    path("nao-conformidades/<int:pk>/aprovacao-pdf/", nao_conformidade_aprovacao_pdf_view, name="nao_conformidade_aprovacao_pdf"),
    path("nao-conformidades/<int:pk>/aprovacao-excel/", nao_conformidade_aprovacao_excel_view, name="nao_conformidade_aprovacao_excel"),

    # PMBOK 12 - Aquisições Estruturadas
    path("fornecedores/", FornecedorListView.as_view(), name="fornecedor_list"),
    path("fornecedores/novo/", FornecedorCreateView.as_view(), name="fornecedor_create"),
    path("solicitacoes-compra/", SolicitacaoCompraListView.as_view(), name="solicitacao_compra_list"),
    path("solicitacoes-compra/exportar/", solicitacao_compra_export_view, name="solicitacao_compra_export"),
    path("solicitacoes-compra/pdf/", solicitacao_compra_lista_pdf_view, name="solicitacao_compra_lista_pdf"),
    path("solicitacoes-compra/nova/", SolicitacaoCompraCreateView.as_view(), name="solicitacao_compra_create"),
    path("solicitacoes-compra/<int:pk>/", SolicitacaoCompraDetailView.as_view(), name="solicitacao_compra_detail"),
    path("solicitacoes-compra/<int:pk>/pdf/", solicitacao_compra_pdf_view, name="solicitacao_compra_pdf"),
    path("cotacoes/", CotacaoListView.as_view(), name="cotacao_list"),
    path("cotacoes/exportar/", cotacao_export_view, name="cotacao_export"),
    path("cotacoes/pdf/", cotacao_lista_pdf_view, name="cotacao_lista_pdf"),
    path("cotacoes/nova/", CotacaoCreateView.as_view(), name="cotacao_create"),
    path("cotacoes/<int:pk>/", CotacaoDetailView.as_view(), name="cotacao_detail"),
    path("cotacoes/<int:pk>/pdf/", cotacao_pdf_view, name="cotacao_pdf"),
    path("ordens-compra/", OrdemCompraListView.as_view(), name="ordem_compra_list"),
    path("ordens-compra/<int:pk>/", OrdemCompraDetailView.as_view(), name="ordem_compra_detail"),
    
    # ISO 6.1 - Gestão de Riscos
    path("riscos/", RiscoListView.as_view(), name="risco_list"),
    path("riscos/novo/", RiscoCreateView.as_view(), name="risco_create"),
    path("riscos/<int:pk>/", RiscoDetailView.as_view(), name="risco_detail"),
    path("riscos/<int:pk>/editar/", RiscoUpdateView.as_view(), name="risco_update"),
    path("riscos/<int:pk>/excluir/", risco_delete_view, name="risco_delete"),
    path("riscos/dashboard/", risco_dashboard_view, name="risco_dashboard"),
    
    # PMBOK 6 / ISO 6.1 - Planejamento Físico
    path("cronogramas/", PlanoFisicoListView.as_view(), name="plano_fisico_list"),
    path("cronogramas/importar/", PlanoFisicoCreateView.as_view(), name="plano_fisico_importar"),
    path("cronogramas/<int:pk>/", PlanoFisicoDetailView.as_view(), name="plano_fisico_detail"),
    path("cronogramas/<int:pk>/editar/", PlanoFisicoUpdateView.as_view(), name="plano_fisico_update"),
    path("cronogramas/<int:pk>/itens/<int:item_pk>/editar/", PlanoFisicoItemUpdateView.as_view(), name="plano_fisico_item_update"),
    path("cronogramas/<int:pk>/baseline/", criar_baseline_view, name="plano_fisico_criar_baseline"),
    path("cronogramas/excluir/", plano_fisico_delete_view, name="plano_fisico_delete"),
    path("cronogramas/dashboard/", PlanoFisicoDashboardView.as_view(), name="plano_fisico_dashboard"),
    
    # Mapeamento Cronograma ↔ EAP
    
    path("mapeamentos/", MapaCorrespondenciaListView.as_view(), name="mapa_correspondencia_list"),
    path("mapeamentos/sugerir/", sugerir_mapeamento_ajax, name="mapa_correspondencia_sugerir"),
    path("mapeamentos/vincular/", vincular_mapeamento_ajax, name="mapa_correspondencia_vincular"),

    # APIs
    path("api/curva-s/", gerar_curva_s_ajax, name="api_curva_s"),
]
