# Generated by Django 6.0.2 on 2026-02-16 01:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('nivel', models.IntegerField(editable=False)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='Construtask.planocontas')),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato (Serviço)'), ('PEDIDO_COMPRA', 'Pedido de Compra (Material)')], max_length=20)),
                ('fornecedor', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_assinatura', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='Construtask.planocontas')),
            ],
        ),
    ]
