# Generated by Django 6.0.2 on 2026-03-04 19:56

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('numero_da_medicao', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('data_medicao', models.DateField()),
                ('valor_medido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='planocontas',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='planocontas',
            name='pai',
        ),
        migrations.AddField(
            model_name='compromisso',
            name='cnpj',
            field=models.CharField(default=1, max_length=18, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compromisso',
            name='descricao',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compromisso',
            name='responsavel',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compromisso',
            name='telefone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planocontas',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planocontas',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planocontas',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='Construtask.planocontas'),
        ),
        migrations.AddField(
            model_name='planocontas',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planocontas',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='Construtask.planocontas'),
        ),
        migrations.AddIndex(
            model_name='planocontas',
            index=models.Index(fields=['codigo'], name='Construtask_codigo_c255d9_idx'),
        ),
        migrations.AddIndex(
            model_name='planocontas',
            index=models.Index(fields=['tree_id', 'lft'], name='Construtask_planocontas_tr2687'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes', to='Construtask.planocontas'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes', to='Construtask.compromisso'),
        ),
    ]
