# Generated by Django 6.0.2 on 2026-03-04 20:23

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0003_alter_planocontas_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocontas',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='Construtask.planocontas'),
        ),
    ]
