# Generated by Django 6.0.2 on 2026-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0004_alter_planocontas_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='descricao',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
