# Generated by Django 6.0.2 on 2026-03-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0005_medicao_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ['-data_medicao'], 'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
    ]
