# Generated by Django 6.0.2 on 2026-03-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0006_alter_medicao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compromisso',
            options={'verbose_name': 'Compras e Contratações', 'verbose_name_plural': 'Compras e Contratações'},
        ),
    ]
