# Generated by Django 6.0.2 on 2026-03-11 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0007_alter_compromisso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planocontas',
            options={'verbose_name': 'Plano de Contas', 'verbose_name_plural': 'Plano de Contas'},
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('serie', models.CharField(blank=True, max_length=10)),
                ('tipo', models.CharField(choices=[('SERVICO', 'Nota de Serviço'), ('MATERIAL', 'Nota de Material')], max_length=20)),
                ('data_emissao', models.DateField()),
                ('fornecedor', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('descricao', models.CharField(max_length=500)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='Construtask.medicao')),
                ('pedido_compra', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PEDIDO_COMPRA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_material', to='Construtask.compromisso')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Construtask.planocontas')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='Construtask.notafiscal')),
            ],
            options={
                'verbose_name': 'Centro de Custo da Nota',
                'verbose_name_plural': 'Centros de Custo da Nota',
            },
        ),
    ]
