# Generated by Django 6.0.2 on 2026-03-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0008_alter_planocontas_options_notafiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalcentrocusto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
