# Generated by Django 6.0.2 on 2026-03-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0009_alter_notafiscalcentrocusto_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromisso',
            old_name='valor',
            new_name='valor_contratado',
        ),
    ]
