# Generated by Django 6.0.2 on 2026-03-25 12:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0010_rename_valor_compromisso_valor_contratado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='valor_contratado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='valor_medido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.CreateModel(
            name='CompromissoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compromisso', to='Construtask.planocontas')),
                ('compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.compromisso')),
            ],
            options={
                'verbose_name': 'Item da Compra/Contratação',
                'verbose_name_plural': 'Itens da Compra/Contratação',
            },
        ),
        migrations.CreateModel(
            name='MedicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_medicao', to='Construtask.planocontas')),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.medicao')),
            ],
            options={
                'verbose_name': 'Item da Medição',
                'verbose_name_plural': 'Itens da Medição',
            },
        ),
    ]
