# Generated by Django 6.0.2 on 2026-03-25 17:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0011_alter_compromisso_valor_contratado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('cliente', models.CharField(blank=True, max_length=150)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('PARALISADA', 'Paralisada'), ('CONCLUIDA', 'Concluida')], default='EM_ANDAMENTO', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.AddField(
            model_name='compromisso',
            name='bloco',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='etapa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execucao'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='torre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='medicao',
            name='bloco',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='medicao',
            name='etapa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medicao',
            name='status',
            field=models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboracao'), ('CONFERIDA', 'Conferida'), ('APROVADA', 'Aprovada'), ('FATURADA', 'Faturada')], default='EM_ELABORACAO', max_length=20),
        ),
        migrations.AddField(
            model_name='medicao',
            name='torre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='bloco',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='etapa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('LANCADA', 'Lancada'), ('CONFERIDA', 'Conferida'), ('PAGA', 'Paga'), ('FECHADA', 'Fechada')], default='LANCADA', max_length=20),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='torre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='HistoricoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compromisso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='Construtask.compromisso')),
                ('medicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='Construtask.medicao')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='Construtask.notafiscal')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Historico Operacional',
                'verbose_name_plural': 'Historicos Operacionais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, upload_to='anexos/%Y/%m')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compromisso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Construtask.compromisso')),
                ('medicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Construtask.medicao')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Construtask.notafiscal')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Anexo Operacional',
                'verbose_name_plural': 'Anexos Operacionais',
            },
        ),
        migrations.AddField(
            model_name='compromisso',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='Construtask.obra'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes', to='Construtask.obra'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='Construtask.obra'),
        ),
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('valor_comprometido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_medido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_notas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('obra', 'ano', 'mes')},
            },
        ),
    ]
