# Generated by Django 6.0.2 on 2026-03-25 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0012_obra_compromisso_bloco_compromisso_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontas',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_contas', to='Construtask.obra'),
        ),
        migrations.AlterField(
            model_name='planocontas',
            name='codigo',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='planocontas',
            constraint=models.UniqueConstraint(fields=('obra', 'codigo'), name='uq_plano_contas_obra_codigo'),
        ),
    ]
