# Generated by Django 6.0.2 on 2026-03-26 12:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0013_planocontas_obra_alter_planocontas_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='data_prevista_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='data_prevista_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='data_prevista_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='data_prevista_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRAZO', 'Prazo'), ('VALOR', 'Valor'), ('ESCOPO', 'Escopo')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=500)),
                ('delta_dias', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='Construtask.compromisso')),
            ],
            options={
                'verbose_name': 'Aditivo Contratual',
                'verbose_name_plural': 'Aditivos Contratuais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AditivoContratoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.aditivocontrato')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos_itens', to='Construtask.planocontas')),
            ],
            options={
                'verbose_name': 'Item de Aditivo',
                'verbose_name_plural': 'Itens de Aditivos',
            },
        ),
    ]
