# Generated by Django 6.0.2 on 2026-03-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0016_criar_empresa_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_empresa', models.BooleanField(default=False, help_text='Se marcado, este usuário pode gerenciar usuários e liberar obras da empresa.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_empresa', to='Construtask.empresa')),
                ('obras_permitidas', models.ManyToManyField(blank=True, help_text='Obras que este usuário pode acessar. Se vazio e não for admin, não terá acesso a nenhuma obra.', related_name='usuarios_permitidos', to='Construtask.obra')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário de Empresa',
                'verbose_name_plural': 'Usuários de Empresa',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
