# Generated by Django 6.0.2 on 2026-03-30 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0019_documento_controle_documental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentorevisao',
            name='uq_documento_versao',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='Construtask_empresa_f6048a_idx',
            old_name='documento_empresa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='Construtask_codigo__012a96_idx',
            old_name='documento_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='documentorevisao',
            new_name='Construtask_documen_7071ed_idx',
            old_name='revisao_doc_status_idx',
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentorevisao',
            unique_together={('documento', 'versao')},
        ),
    ]
