# Generated by Django 6.0.2 on 2026-03-31 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0021_risco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_rateio', models.DecimalField(decimal_places=2, default=100, help_text='% do item do cronograma que corresponde ao centro de custo', max_digits=5)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mapeamento Cronograma ↔ Orçamento',
                'verbose_name_plural': 'Mapeamentos Cronograma ↔ Orçamento',
                'ordering': ['plano_fisico_item'],
            },
        ),
        migrations.CreateModel(
            name='MapaCorrespondenciaRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='% de rateio para este centro de custo', max_digits=5)),
            ],
            options={
                'verbose_name': 'Rateio de Mapeamento',
                'verbose_name_plural': 'Rateios de Mapeamento',
            },
        ),
        migrations.CreateModel(
            name='PlanoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do cronograma', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_origem', models.FileField(blank=True, help_text='Arquivo original importado (MPP/XLSX)', null=True, upload_to='cronogramas/%Y/%m')),
                ('tipo_arquivo', models.CharField(blank=True, choices=[('XLSX', 'Excel (.xlsx)'), ('MPP', 'Microsoft Project (.mpp)')], max_length=10)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('is_baseline', models.BooleanField(default=False, help_text='Indica se este cronograma é um baseline')),
                ('data_base', models.DateField(blank=True, help_text='Data base do cronograma', null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('OBSOLETO', 'Obsoleto'), ('BASELINE', 'Baseline')], default='RASCUNHO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cronograma Físico',
                'verbose_name_plural': 'Cronogramas Físicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanoFisicoBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField()),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='cronogramas/baselines/%Y/%m')),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Baseline do Cronograma',
                'verbose_name_plural': 'Baselines dos Cronogramas',
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='PlanoFisicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_atividade', models.CharField(help_text='Código da atividade (do arquivo)', max_length=50)),
                ('atividade', models.CharField(help_text='Nome da atividade', max_length=500)),
                ('predecessor', models.CharField(blank=True, help_text='Código da predecessora', max_length=50)),
                ('successor', models.CharField(blank=True, help_text='Código da sucessora', max_length=50)),
                ('duracao', models.PositiveIntegerField(default=0, help_text='Duração em dias')),
                ('data_inicio_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('percentual_concluido', models.PositiveSmallIntegerField(default=0, help_text='Percentual concluído (0-100)')),
                ('is_marco', models.BooleanField(default=False, help_text='Indica se é um marco')),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('wbs_code', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('valor_planejado', models.DecimalField(decimal_places=2, default=0, help_text='Valor planejado da atividade', max_digits=15)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, help_text='Valor realizado da atividade', max_digits=15)),
                ('dias_desvio', models.IntegerField(default=0, help_text='Dias de desvio (positivo = atraso)')),
                ('percent_desvio', models.DecimalField(decimal_places=2, default=0, help_text='% de desvio', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atividade do Cronograma',
                'verbose_name_plural': 'Atividades do Cronograma',
                'ordering': ['plano', 'sort_order'],
            },
        ),
        migrations.RenameIndex(
            model_name='risco',
            new_name='Construtask_empresa_321cb7_idx',
            old_name='risco_empresa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='risco',
            new_name='Construtask_nivel_b42faf_idx',
            old_name='risco_nivel_idx',
        ),
        migrations.AddField(
            model_name='mapacorrespondencia',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapacorrespondencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='Construtask.empresa'),
        ),
        migrations.AddField(
            model_name='mapacorrespondencia',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='Construtask.obra'),
        ),
        migrations.AddField(
            model_name='mapacorrespondencia',
            name='plano_contas',
            field=models.ForeignKey(blank=True, help_text='Centro de custo da EAP (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapeamentos', to='Construtask.planocontas'),
        ),
        migrations.AddField(
            model_name='mapacorrespondenciarateio',
            name='correspondencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='Construtask.mapacorrespondencia'),
        ),
        migrations.AddField(
            model_name='mapacorrespondenciarateio',
            name='plano_contas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios_recebidos', to='Construtask.planocontas'),
        ),
        migrations.AddField(
            model_name='planofisico',
            name='baseline_de',
            field=models.ForeignKey(blank=True, help_text='Qual baseline originou esta versão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines', to='Construtask.planofisico'),
        ),
        migrations.AddField(
            model_name='planofisico',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_fisicos', to='Construtask.obra'),
        ),
        migrations.AddField(
            model_name='planofisico',
            name='responsavel_importacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronogramas_importados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planofisicobaseline',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_baseline', to='Construtask.planofisico'),
        ),
        migrations.AddField(
            model_name='planofisicobaseline',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planofisicoitem',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.planofisico'),
        ),
        migrations.AddField(
            model_name='planofisicoitem',
            name='plano_contas',
            field=models.ForeignKey(blank=True, help_text='Item da EAP vinculado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cronograma', to='Construtask.planocontas'),
        ),
        migrations.AddField(
            model_name='mapacorrespondencia',
            name='plano_fisico_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='Construtask.planofisicoitem'),
        ),
        migrations.AlterUniqueTogether(
            name='mapacorrespondenciarateio',
            unique_together={('correspondencia', 'plano_contas')},
        ),
        migrations.AddIndex(
            model_name='planofisico',
            index=models.Index(fields=['obra', 'status'], name='Construtask_obra_id_c05d02_idx'),
        ),
        migrations.AddIndex(
            model_name='planofisico',
            index=models.Index(fields=['obra', 'is_baseline'], name='Construtask_obra_id_17cc89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planofisicobaseline',
            unique_together={('plano', 'versao')},
        ),
        migrations.AddIndex(
            model_name='planofisicoitem',
            index=models.Index(fields=['plano', 'codigo_atividade'], name='Construtask_plano_i_6cacc8_idx'),
        ),
        migrations.AddIndex(
            model_name='planofisicoitem',
            index=models.Index(fields=['plano', 'data_inicio_prevista'], name='Construtask_plano_i_33b6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='mapacorrespondencia',
            index=models.Index(fields=['plano_fisico_item', 'status'], name='Construtask_plano_f_b82900_idx'),
        ),
        migrations.AddIndex(
            model_name='mapacorrespondencia',
            index=models.Index(fields=['plano_contas', 'status'], name='Construtask_plano_c_5dc4ec_idx'),
        ),
    ]
