# Generated by Django 6.0.2 on 2026-03-31 20:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0022_planejamento_fisico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, max_length=180)),
                ('cnpj', models.CharField(max_length=18)),
                ('contato', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='Construtask.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
                'unique_together': {('empresa', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='EM_ANALISE', max_length=20)),
                ('data_cotacao', models.DateField()),
                ('validade_ate', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='Construtask.empresa')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='Construtask.obra')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='Construtask.fornecedor')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-data_cotacao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('avaliado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='Construtask.fornecedor')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_fornecedores', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Avaliação de Fornecedor',
                'verbose_name_plural': 'Avaliações de Fornecedor',
                'ordering': ['-avaliado_em'],
            },
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('causa', models.TextField(blank=True)),
                ('acao_corretiva', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_TRATAMENTO', 'Em Tratamento'), ('EM_VERIFICACAO', 'Em Verificação'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('data_abertura', models.DateField(default=django.utils.timezone.localdate)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nao_conformidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nao_conformidades', to='Construtask.empresa')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nao_conformidades', to='Construtask.obra')),
                ('plano_contas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nao_conformidades', to='Construtask.planocontas')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nao_conformidades_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Não Conformidade',
                'verbose_name_plural': 'Não Conformidades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NaoConformidadeHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ABERTURA', 'Abertura'), ('TRATAMENTO', 'Tratamento'), ('VERIFICACAO', 'Verificação'), ('ENCERRAMENTO', 'Encerramento'), ('CANCELAMENTO', 'Cancelamento'), ('ATUALIZACAO', 'Atualização')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nao_conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Construtask.naoconformidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Não Conformidade',
                'verbose_name_plural': 'Históricos de Não Conformidade',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('EMITIDA', 'Emitida'), ('PARCIAL', 'Parcial'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='EMITIDA', max_length=20)),
                ('data_emissao', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compromisso_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_compra_estruturadas', to='Construtask.compromisso')),
                ('cotacao_aprovada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra', to='Construtask.cotacao')),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra_emitidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_compra', to='Construtask.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra', to='Construtask.fornecedor')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_compra', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
                'ordering': ['-data_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdemCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ordem_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.ordemcompra')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ordem_compra', to='Construtask.planocontas')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADA', 'Aprovada'), ('COTANDO', 'Em Cotação'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('data_solicitacao', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_compra', to='Construtask.empresa')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_compra', to='Construtask.obra')),
                ('plano_contas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_compra', to='Construtask.planocontas')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Compra',
                'verbose_name_plural': 'Solicitações de Compra',
                'ordering': ['-data_solicitacao', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra', to='Construtask.solicitacaocompra'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='Construtask.solicitacaocompra'),
        ),
        migrations.CreateModel(
            name='SolicitacaoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_estimado_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao', to='Construtask.planocontas')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.solicitacaocompra')),
            ],
        ),
        migrations.CreateModel(
            name='CotacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('prazo_entrega_dias', models.PositiveIntegerField(default=0)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.cotacao')),
                ('item_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='Construtask.solicitacaocompraitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='naoconformidade',
            index=models.Index(fields=['empresa', 'obra', 'status'], name='Construtask_empresa_1b2e62_idx'),
        ),
        migrations.AddIndex(
            model_name='naoconformidade',
            index=models.Index(fields=['obra', 'data_abertura'], name='Construtask_obra_id_430eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaocompra',
            index=models.Index(fields=['empresa', 'obra', 'status'], name='Construtask_empresa_b9e835_idx'),
        ),
    ]
