# Generated by Django 6.0.2 on 2026-04-01 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0023_fornecedor_cotacao_fornecedoravaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromissoitem',
            name='descricao_tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='justificativa_escolha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitacaocompraitem',
            name='descricao_tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CotacaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('arquivo', models.FileField(upload_to='cotacoes/%Y/%m')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Construtask.cotacao')),
            ],
            options={
                'verbose_name': 'Anexo da Cotação',
                'verbose_name_plural': 'Anexos das Cotações',
                'ordering': ['id'],
            },
        ),
    ]
