# Generated by Django 6.0.2 on 2026-04-08 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0025_historicooperacional_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='enviado_para_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='enviado_para_aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_enviados_para_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicao',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicao',
            name='enviado_para_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='enviado_para_aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicoes_enviadas_para_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='papel_aprovacao',
            field=models.CharField(choices=[('GERENTE_OBRAS', 'Gerente de Obras'), ('COORDENADOR_OBRAS', 'Coordenador de Obras'), ('ENGENHEIRO_OBRAS', 'Engenheiro de Obras'), ('TECNICO_OBRAS', 'Tecnico de Obras')], default='TECNICO_OBRAS', help_text='Define a alcada de aprovacao operacional do usuario.', max_length=30),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovacao'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execucao'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='status',
            field=models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboracao'), ('EM_APROVACAO', 'Em Aprovacao'), ('CONFERIDA', 'Conferida'), ('APROVADA', 'Aprovada'), ('FATURADA', 'Faturada')], default='EM_ELABORACAO', max_length=20),
        ),
    ]
