# Generated by Django 6.0.2 on 2026-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0026_compromisso_aprovado_em_compromisso_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='parecer_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='parecer_aprovacao',
            field=models.TextField(blank=True),
        ),
    ]
