# Generated by Django 6.0.2 on 2026-04-08 13:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0027_compromisso_parecer_aprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines_orcamento_criadas', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines_orcamento', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Baseline de Orcamento',
                'verbose_name_plural': 'Baselines de Orcamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoBaselineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('parent_codigo', models.CharField(blank=True, max_length=50)),
                ('level', models.PositiveIntegerField(default=0)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('valor_total_consolidado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Construtask.orcamentobaseline')),
            ],
            options={
                'verbose_name': 'Item da Baseline de Orcamento',
                'verbose_name_plural': 'Itens da Baseline de Orcamento',
                'ordering': ['codigo'],
            },
        ),
    ]
