# Generated by Django 6.0.2 on 2026-04-08 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0028_orcamentobaseline_orcamentobaselineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentobaseline',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamentobaseline',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines_orcamento_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamentobaseline',
            name='enviado_para_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamentobaseline',
            name='enviado_para_aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines_orcamento_enviadas_para_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamentobaseline',
            name='is_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamentobaseline',
            name='parecer_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamentobaseline',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovacao'), ('APROVADA', 'Aprovada')], default='RASCUNHO', max_length=20),
        ),
    ]
