# Generated by Django 6.0.2 on 2026-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0029_orcamentobaseline_aprovado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
