# Generated by Django 6.0.2 on 2026-04-10 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0031_naoconformidade_numero_planofisico_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivocontrato',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='enviado_para_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='enviado_para_aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_enviados_para_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='parecer_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovacao'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20),
        ),
    ]
