# Generated by Django 6.0.2 on 2026-04-10 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0032_aditivocontrato_aprovado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['-data_cotacao', '-id'], 'verbose_name': 'CotaÃ§Ã£o', 'verbose_name_plural': 'CotaÃ§Ãµes'},
        ),
        migrations.AlterModelOptions(
            name='cotacaoanexo',
            options={'ordering': ['id'], 'verbose_name': 'Anexo da CotaÃ§Ã£o', 'verbose_name_plural': 'Anexos das CotaÃ§Ãµes'},
        ),
        migrations.AlterModelOptions(
            name='fornecedoravaliacao',
            options={'ordering': ['-avaliado_em'], 'verbose_name': 'AvaliaÃ§Ã£o de Fornecedor', 'verbose_name_plural': 'AvaliaÃ§Ãµes de Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaocompra',
            options={'ordering': ['-data_solicitacao', '-id'], 'verbose_name': 'SolicitaÃ§Ã£o de Compra', 'verbose_name_plural': 'SolicitaÃ§Ãµes de Compra'},
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_compra_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='enviado_para_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='enviado_para_aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_compra_enviadas_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='parecer_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em AnÃ¡lise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='EM_ANALISE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADA', 'Aprovada'), ('PARCIAL', 'Parcial'), ('CONCLUIDA', 'ConcluÃ\xadda'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADA', 'Aprovada'), ('COTANDO', 'Em CotaÃ§Ã£o'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
    ]
