# Generated by Django 6.0.2 on 2026-04-10 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0033_alter_cotacao_options_alter_cotacaoanexo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivocontrato',
            name='impacto_resumido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='motivo_mudanca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='solicitado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='eficacia_observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='eficacia_verificada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='eficacia_verificada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nao_conformidades_eficacia_verificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='evidencia_encerramento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='evidencia_tratamento',
            field=models.TextField(blank=True),
        ),
    ]
