# Generated by Django 6.0.2 on 2026-04-10 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0034_aditivocontrato_impacto_resumido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcessoDadoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_titular', models.CharField(choices=[('USUARIO', 'Usuario'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('TERCEIRO', 'Terceiro')], max_length=20)),
                ('entidade', models.CharField(max_length=120)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('identificador', models.CharField(blank=True, max_length=255)),
                ('acao', models.CharField(choices=[('VIEW', 'Visualizacao'), ('EXPORT', 'Exportacao'), ('DOWNLOAD', 'Download'), ('ADMIN_LIST', 'Consulta Administrativa')], default='VIEW', max_length=20)),
                ('finalidade', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_dados_pessoais', to='Construtask.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_dados_pessoais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acesso a Dado Pessoal',
                'verbose_name_plural': 'Registros de Acesso a Dados Pessoais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='Construtask_empresa_2c8fd4_idx'), models.Index(fields=['usuario', 'criado_em'], name='Construtask_usuario_f70b54_idx'), models.Index(fields=['categoria_titular', 'acao'], name='Construtask_categor_a9b92b_idx')],
            },
        ),
    ]
