# Generated by Django 6.0.2 on 2026-04-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0035_registroacessodadopessoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_regra', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], default='MEDIA', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_TRATAMENTO', 'Em Tratamento'), ('JUSTIFICADO', 'Justificado'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=20)),
                ('entidade_tipo', models.CharField(blank=True, max_length=80)),
                ('entidade_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia', models.CharField(max_length=120)),
                ('evidencias', models.JSONField(blank=True, default=dict)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_operacionais', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Alerta Operacional',
                'verbose_name_plural': 'Alertas Operacionais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['obra', 'codigo_regra', 'status'], name='Construtask_obra_id_e79718_idx'), models.Index(fields=['obra', 'severidade', 'status'], name='Construtask_obra_id_465ae5_idx')],
                'constraints': [models.UniqueConstraint(fields=('obra', 'codigo_regra', 'referencia'), name='uq_alerta_operacional_regra_ref')],
            },
        ),
    ]
