# Generated by Django 6.0.2 on 2026-04-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0036_alertaoperacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapacorrespondencia',
            options={'ordering': ['plano_fisico_item'], 'verbose_name': 'Mapeamento Cronograma ↔ Orcamento', 'verbose_name_plural': 'Mapeamentos Cronograma ↔ Orcamento'},
        ),
        migrations.AlterModelOptions(
            name='planofisico',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cronograma Fisico', 'verbose_name_plural': 'Cronogramas Fisicos'},
        ),
        migrations.AlterModelOptions(
            name='planofisicoitem',
            options={'ordering': ['plano', 'sort_order', 'pk'], 'verbose_name': 'Atividade do Cronograma', 'verbose_name_plural': 'Atividades do Cronograma'},
        ),
        migrations.AddField(
            model_name='planofisicoitem',
            name='codigo_eap_importado',
            field=models.CharField(blank=True, help_text='Codigo da EAP informado no arquivo importado', max_length=100),
        ),
        migrations.AddField(
            model_name='planofisicoitem',
            name='erro_vinculo_eap',
            field=models.CharField(blank=True, help_text='Erro de vinculo quando o codigo da EAP nao existir', max_length=255),
        ),
        migrations.AddField(
            model_name='planofisicoitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Item pai na hierarquia do cronograma', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='Construtask.planofisicoitem'),
        ),
        migrations.AlterField(
            model_name='planofisico',
            name='baseline_de',
            field=models.ForeignKey(blank=True, help_text='Qual baseline originou esta versao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines', to='Construtask.planofisico'),
        ),
        migrations.AlterField(
            model_name='planofisico',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='Indica se este cronograma e um baseline'),
        ),
        migrations.AlterField(
            model_name='planofisico',
            name='titulo',
            field=models.CharField(help_text='Titulo do cronograma', max_length=200),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='codigo_atividade',
            field=models.CharField(help_text='Codigo da atividade (do arquivo)', max_length=50),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='duracao',
            field=models.PositiveIntegerField(default=0, help_text='Duracao planejada em dias'),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='is_marco',
            field=models.BooleanField(default=False, help_text='Indica se e um marco'),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='percent_desvio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='percentual_concluido',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentual realizado informado para a atividade (0-100)'),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='predecessor',
            field=models.CharField(blank=True, help_text='Codigo da predecessora', max_length=50),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='successor',
            field=models.CharField(blank=True, help_text='Codigo da sucessora', max_length=50),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='valor_planejado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='valor_realizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddIndex(
            model_name='planofisicoitem',
            index=models.Index(fields=['plano', 'parent', 'sort_order'], name='Construtask_plano_i_12e403_idx'),
        ),
    ]
