# Generated by Django 6.0.2 on 2026-04-13 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0037_alter_mapacorrespondencia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaoperacional',
            name='observacao_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alertaoperacional',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_operacionais_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertaoperacional',
            name='ultima_acao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertaoperacional',
            name='ultima_acao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_operacionais_movimentados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AlertaOperacionalHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criacao'), ('TRATAMENTO', 'Em Tratamento'), ('JUSTIFICATIVA', 'Justificativa'), ('ENCERRAMENTO', 'Encerramento'), ('REABERTURA', 'Reabertura')], max_length=20)),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(blank=True, max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='Construtask.alertaoperacional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_alertas_operacionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico de Alerta Operacional',
                'verbose_name_plural': 'Historicos de Alertas Operacionais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['alerta', 'criado_em'], name='Construtask_alerta__2cd7f7_idx'), models.Index(fields=['acao'], name='Construtask_acao_f8beb1_idx')],
            },
        ),
    ]
