# Generated by Django 6.0.2 on 2026-04-13 20:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0038_alertaoperacional_observacao_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroAlertaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planejamento_suprimentos_janela_dias', models.PositiveIntegerField(default=60)),
                ('contrato_sem_medicao_dias', models.PositiveIntegerField(default=15)),
                ('medicao_sem_nota_dias', models.PositiveIntegerField(default=7)),
                ('nota_sem_rateio_percentual_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=5)),
                ('risco_vencido_tolerancia_dias', models.PositiveIntegerField(default=0)),
                ('nao_conformidade_sem_evolucao_dias', models.PositiveIntegerField(default=15)),
                ('atividade_sem_avanco_tolerancia_dias', models.PositiveIntegerField(default=0)),
                ('desvio_prazo_percentual_minimo_previsto', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('desvio_prazo_tolerancia_percentual', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('estouro_prazo_tolerancia_dias', models.PositiveIntegerField(default=0)),
                ('desvio_custo_tolerancia_percentual', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('custo_sem_avanco_valor_minimo', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14)),
                ('compromisso_acima_orcado_tolerancia_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('acumulo_riscos_quantidade_minima', models.PositiveIntegerField(default=5)),
                ('acumulo_riscos_quantidade_critica', models.PositiveIntegerField(default=8)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_alerta', to='Construtask.empresa')),
            ],
            options={
                'verbose_name': 'Parametro de Alerta da Empresa',
                'verbose_name_plural': 'Parametros de Alertas da Empresa',
            },
        ),
    ]
