# Generated by Django 6.0.2 on 2026-04-13 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0039_parametroalertaempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroalertaempresa',
            name='custo_sem_avanco_valor_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
