# Generated by Django 6.0.2 on 2026-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0040_alter_parametroalertaempresa_custo_sem_avanco_valor_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroalertaempresa',
            name='alerta_prazo_solucao_dias',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='parametroalertaempresa',
            name='alerta_sem_workflow_dias',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
