# Generated by Django 6.0.2 on 2026-04-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0041_parametroalertaempresa_alerta_prazo_solucao_dias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='enviado_para_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='enviado_para_aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_enviadas_para_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='parecer_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='anonimizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='descartado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='exclusao_logica_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_compra_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='enviado_para_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='enviado_para_aprovacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_compra_enviadas_para_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaocompra',
            name='parecer_aprovacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovacao'), ('EM_ANALISE', 'Em AnÃ¡lise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovacao'), ('APROVADA', 'Aprovada'), ('COTANDO', 'Em CotaÃ§Ã£o'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_titular', models.CharField(choices=[('USUARIO', 'Usuario'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('TERCEIRO', 'Terceiro')], max_length=20)),
                ('email_referencia', models.EmailField(blank=True, max_length=254)),
                ('finalidade', models.CharField(max_length=255)),
                ('texto_aceito', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_lgpd', to='Construtask.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimentos_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimento LGPD',
                'verbose_name_plural': 'Consentimentos LGPD',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'categoria_titular'], name='Construtask_empresa_c0cfc7_idx'), models.Index(fields=['email_referencia', 'revogado_em'], name='Construtask_email_r_2c2bc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissaoModuloAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=50)),
                ('permitido', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_modulo_concedidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulo', to='Construtask.usuarioempresa')),
            ],
            options={
                'verbose_name': 'Permissao por Modulo',
                'verbose_name_plural': 'Permissoes por Modulo',
                'ordering': ['modulo', 'acao'],
                'unique_together': {('usuario_empresa', 'modulo', 'acao')},
            },
        ),
        migrations.CreateModel(
            name='RegistroTratamentoDadoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_titular', models.CharField(choices=[('USUARIO', 'Usuario'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('TERCEIRO', 'Terceiro')], max_length=20)),
                ('entidade', models.CharField(max_length=120)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('identificador', models.CharField(blank=True, max_length=255)),
                ('acao', models.CharField(choices=[('CONSULTA', 'Consulta'), ('ANONIMIZACAO', 'Anonimizacao'), ('EXCLUSAO_LOGICA', 'Exclusao logica'), ('DESCARTE', 'Descarte'), ('CONSENTIMENTO', 'Consentimento'), ('REVOGACAO_CONSENTIMENTO', 'Revogacao de consentimento')], max_length=30)),
                ('finalidade', models.CharField(max_length=255)),
                ('base_legal', models.CharField(blank=True, max_length=255)),
                ('detalhes', models.TextField(blank=True)),
                ('evidencia', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos_lgpd', to='Construtask.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos_lgpd_executados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Tratamento LGPD',
                'verbose_name_plural': 'Registros de Tratamento LGPD',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='Construtask_empresa_0770fa_idx'), models.Index(fields=['categoria_titular', 'acao'], name='Construtask_categor_d2926d_idx'), models.Index(fields=['entidade', 'objeto_id'], name='Construtask_entidad_75707d_idx')],
            },
        ),
    ]
