# Generated by Django 6.0.2 on 2026-04-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0042_cotacao_aprovado_em_cotacao_aprovado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoRegraOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_regra', models.CharField(max_length=40)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('entidade_tipo', models.CharField(blank=True, max_length=80)),
                ('entidade_id', models.PositiveIntegerField(blank=True, null=True)),
                ('severidade', models.CharField(blank=True, max_length=20)),
                ('status_alerta', models.CharField(blank=True, max_length=20)),
                ('resultado', models.CharField(choices=[('CRIADO', 'Criado'), ('ATUALIZADO', 'Atualizado'), ('ENCERRADO', 'Encerrado'), ('REATIVADO', 'Reativado')], max_length=20)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_automacao', to='Construtask.alertaoperacional')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_regras_operacionais', to='Construtask.obra')),
            ],
            options={
                'verbose_name': 'Execucao de Regra Operacional',
                'verbose_name_plural': 'Execucoes de Regras Operacionais',
                'ordering': ['-executado_em'],
                'indexes': [models.Index(fields=['obra', 'codigo_regra', 'executado_em'], name='Construtask_obra_id_7c9861_idx'), models.Index(fields=['resultado', 'executado_em'], name='Construtask_resulta_ca8438_idx'), models.Index(fields=['alerta', 'executado_em'], name='Construtask_alerta__2df2b3_idx')],
            },
        ),
    ]
