# Generated by Django 6.0.2 on 2026-04-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0043_execucaoregraoperacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaoperacional',
            name='prazo_solucao_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
