# Generated by Django 6.0.2 on 2026-04-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0044_alertaoperacional_prazo_solucao_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssincrono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SINCRONIZAR_ALERTAS_OBRA', 'Sincronizar alertas da obra'), ('IMPORTAR_PLANO_CONTAS', 'Importar plano de contas'), ('GERAR_RELATORIO_FINANCEIRO', 'Gerar relatorio financeiro')], max_length=40)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em execucao'), ('CONCLUIDO', 'Concluido'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo_entrada', models.FileField(blank=True, null=True, upload_to='jobs/input/')),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='jobs/output/')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='Construtask.empresa')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='Construtask.obra')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assincronos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Assincrono',
                'verbose_name_plural': 'Jobs Assincronos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'tipo', 'criado_em'], name='Construtask_status_d626d9_idx'), models.Index(fields=['empresa', 'obra', 'criado_em'], name='Construtask_empresa_b06ef3_idx')],
            },
        ),
    ]
