# Generated by Django 6.0.2 on 2026-04-17 18:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0045_jobassincrono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=50)),
                ('metodo', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField()),
                ('duracao_ms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas_requisicao', to='Construtask.empresa')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas_requisicao', to='Construtask.obra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metricas_requisicao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metrica de Requisicao',
                'verbose_name_plural': 'Metricas de Requisicao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['metodo', 'status_code', 'criado_em'], name='Construtask_metodo_f2f676_idx'), models.Index(fields=['empresa', 'obra', 'criado_em'], name='Construtask_empresa_115cc8_idx'), models.Index(fields=['request_id'], name='Construtask_request_96a94d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RastroErroAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=50)),
                ('metodo', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField(default=500)),
                ('classe_erro', models.CharField(max_length=120)),
                ('mensagem', models.TextField()),
                ('stacktrace', models.TextField(blank=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rastros_erro', to='Construtask.empresa')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rastros_erro', to='Construtask.obra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rastros_erro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rastro de Erro da Aplicacao',
                'verbose_name_plural': 'Rastros de Erro da Aplicacao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['classe_erro', 'criado_em'], name='Construtask_classe__5dc892_idx'), models.Index(fields=['empresa', 'obra', 'criado_em'], name='Construtask_empresa_6fd7c4_idx'), models.Index(fields=['request_id'], name='Construtask_request_ff68d4_idx'), models.Index(fields=['resolvido', 'criado_em'], name='Construtask_resolvi_0788c7_idx')],
            },
        ),
    ]
