# Generated by Django 6.0.2 on 2026-04-17 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0046_metricarequisicao_rastroerroaplicacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoBackupSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BACKUP', 'Backup'), ('TESTE_RESTAURACAO', 'Teste de recuperacao')], max_length=30)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHOU', 'Falhou'), ('PARCIAL', 'Parcial')], default='SUCESSO', max_length=20)),
                ('ambiente', models.CharField(default='development', max_length=30)),
                ('provedor', models.CharField(blank=True, max_length=80)),
                ('identificador_artefato', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('observacao', models.TextField(blank=True)),
                ('executado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('backup_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testes_restauracao', to='Construtask.operacaobackupsaas')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_backup_saas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operacao de Backup SaaS',
                'verbose_name_plural': 'Operacoes de Backup SaaS',
                'ordering': ['-executado_em'],
                'indexes': [models.Index(fields=['tipo', 'status', 'executado_em'], name='Construtask_tipo_dfe3c0_idx'), models.Index(fields=['ambiente', 'executado_em'], name='Construtask_ambient_cbb48a_idx'), models.Index(fields=['provedor', 'executado_em'], name='Construtask_provedo_e5df6c_idx')],
            },
        ),
    ]
