# Generated by Codex on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Construtask", "0047_operacaobackupsaas"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(fields=["obra", "tipo", "status"], name="Construtask_obra_id_241b65_idx"),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(fields=["obra", "data_assinatura"], name="Construtask_obra_id_3a4ca9_idx"),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(fields=["obra", "fornecedor"], name="Construtask_obra_id_c3a265_idx"),
        ),
        migrations.AddIndex(
            model_name="compromisso",
            index=models.Index(fields=["obra", "cnpj"], name="Construtask_obra_id_998c78_idx"),
        ),
        migrations.AddIndex(
            model_name="medicao",
            index=models.Index(fields=["obra", "status", "data_medicao"], name="Construtask_obra_id_46b2df_idx"),
        ),
        migrations.AddIndex(
            model_name="medicao",
            index=models.Index(fields=["contrato", "data_medicao"], name="Construtask_contrat_873d90_idx"),
        ),
        migrations.AddIndex(
            model_name="medicao",
            index=models.Index(fields=["obra", "fornecedor"], name="Construtask_obra_id_e8ab93_idx"),
        ),
        migrations.AddIndex(
            model_name="metricarequisicao",
            index=models.Index(fields=["path", "criado_em"], name="Construtask_path_35aca1_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["obra", "status", "data_emissao"], name="Construtask_obra_id_6a2431_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["medicao", "data_emissao"], name="Construtask_medicao_9434d6_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["pedido_compra", "data_emissao"], name="Construtask_pedido__09e519_idx"),
        ),
        migrations.AddIndex(
            model_name="notafiscal",
            index=models.Index(fields=["obra", "fornecedor"], name="Construtask_obra_id_ce97d2_idx"),
        ),
        migrations.AddIndex(
            model_name="obra",
            index=models.Index(fields=["empresa", "status"], name="Construtask_empresa_c51ea2_idx"),
        ),
        migrations.AddIndex(
            model_name="rastroerroaplicacao",
            index=models.Index(fields=["path", "criado_em"], name="Construtask_path_f56878_idx"),
        ),
        migrations.AddIndex(
            model_name="usuarioempresa",
            index=models.Index(fields=["empresa", "is_admin_empresa"], name="Construtask_empresa_ecd57e_idx"),
        ),
        migrations.AddIndex(
            model_name="usuarioempresa",
            index=models.Index(fields=["empresa", "papel_aprovacao"], name="Construtask_empresa_f334a3_idx"),
        ),
    ]
