# Generated by Django 6.0.2 on 2026-04-18 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Construtask", "0048_etapa2_indices_operacionais"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametroComunicacaoEmpresa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("frequencia_curto_prazo_dias", models.PositiveIntegerField(default=7)),
                ("frequencia_medio_prazo_dias", models.PositiveIntegerField(default=30)),
                ("frequencia_longo_prazo_dias", models.PositiveIntegerField(default=90)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("empresa", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="parametros_comunicacao", to="Construtask.empresa")),
            ],
            options={
                "verbose_name": "Parametro de Comunicacao da Empresa",
                "verbose_name_plural": "Parametros de Comunicacao da Empresa",
            },
        ),
        migrations.CreateModel(
            name="ReuniaoComunicacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(blank=True, max_length=30, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("tipo_reuniao", models.CharField(choices=[("CURTO_PRAZO", "Curto Prazo"), ("MEDIO_PRAZO", "Medio Prazo"), ("LONGO_PRAZO", "Longo Prazo")], max_length=20)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("EM_APROVACAO", "Em Aprovacao"), ("APROVADA", "Aprovada")], default="RASCUNHO", max_length=20)),
                ("periodicidade_dias", models.PositiveIntegerField(default=7)),
                ("data_prevista", models.DateField(default=django.utils.timezone.localdate)),
                ("data_realizada", models.DateField(blank=True, null=True)),
                ("pauta_resumo", models.TextField(blank=True)),
                ("ata_texto", models.TextField(blank=True)),
                ("pauta_validada_em", models.DateTimeField(blank=True, null=True)),
                ("enviado_para_aprovacao_em", models.DateTimeField(blank=True, null=True)),
                ("parecer_aprovacao", models.TextField(blank=True)),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("aprovado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reunioes_comunicacao_aprovadas", to=settings.AUTH_USER_MODEL)),
                ("criado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reunioes_comunicacao_criadas", to=settings.AUTH_USER_MODEL)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reunioes_comunicacao", to="Construtask.empresa")),
                ("enviado_para_aprovacao_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reunioes_comunicacao_enviadas_aprovacao", to=settings.AUTH_USER_MODEL)),
                ("obra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reunioes_comunicacao", to="Construtask.obra")),
                ("pauta_validada_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reunioes_comunicacao_validadas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Reuniao de Comunicacao",
                "verbose_name_plural": "Reunioes de Comunicacao",
                "ordering": ["-data_prevista", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemPautaReuniao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("origem_tipo", models.CharField(choices=[("AUTOMATICA", "Automatica"), ("MANUAL", "Manual")], default="AUTOMATICA", max_length=20)),
                ("categoria", models.CharField(choices=[("ALERTA", "Alerta"), ("RISCO", "Risco"), ("NAO_CONFORMIDADE", "Nao Conformidade"), ("CRONOGRAMA", "Cronograma"), ("CONTRATO", "Contrato"), ("MEDICAO", "Medicao"), ("OUTRO", "Outro")], default="OUTRO", max_length=30)),
                ("referencia_modelo", models.CharField(blank=True, max_length=100)),
                ("referencia_id", models.PositiveIntegerField(blank=True, null=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                ("resposta_o_que", models.TextField(blank=True)),
                ("resposta_quem", models.CharField(blank=True, max_length=180)),
                ("resposta_quando", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("reuniao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens_pauta", to="Construtask.reuniaocomunicacao")),
            ],
            options={
                "verbose_name": "Item de Pauta",
                "verbose_name_plural": "Itens de Pauta",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoReuniaoComunicacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("acao", models.CharField(choices=[("CRIACAO", "Criacao"), ("PAUTA_VALIDADA", "Pauta Validada"), ("PAUTA_ATUALIZADA", "Pauta Atualizada"), ("ENVIO_APROVACAO", "Envio para Aprovacao"), ("APROVACAO", "Aprovacao"), ("AJUSTE", "Retorno para Ajuste")], max_length=30)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("reuniao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historicos", to="Construtask.reuniaocomunicacao")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="historicos_reunioes_comunicacao", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Historico de Reuniao de Comunicacao",
                "verbose_name_plural": "Historicos de Reunioes de Comunicacao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="reuniaocomunicacao",
            index=models.Index(fields=["empresa", "obra", "tipo_reuniao", "status"], name="Construtask_empresa_124e9a_idx"),
        ),
        migrations.AddIndex(
            model_name="reuniaocomunicacao",
            index=models.Index(fields=["obra", "data_prevista"], name="Construtask_obra_id_a1be60_idx"),
        ),
        migrations.AddIndex(
            model_name="itempautareuniao",
            index=models.Index(fields=["reuniao", "ativo", "categoria"], name="Construtask_reuniao_7bd3e3_idx"),
        ),
        migrations.AddIndex(
            model_name="itempautareuniao",
            index=models.Index(fields=["reuniao", "origem_tipo", "referencia_modelo", "referencia_id"], name="Construtask_reuniao_4ec09e_idx"),
        ),
        migrations.AddIndex(
            model_name="historicoreuniaocomunicacao",
            index=models.Index(fields=["reuniao", "criado_em"], name="Construtask_reuniao_3e32c4_idx"),
        ),
        migrations.AddIndex(
            model_name="historicoreuniaocomunicacao",
            index=models.Index(fields=["acao"], name="Construtask_acao_4b0295_idx"),
        ),
    ]
