# Generated by Django 6.0.2 on 2026-04-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0050_reuniao_comunicacao_pauta_validada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compromisso',
            options={'verbose_name': 'Compras e ContrataÃ§Ãµes', 'verbose_name_plural': 'Compras e ContrataÃ§Ãµes'},
        ),
        migrations.AlterModelOptions(
            name='compromissoitem',
            options={'verbose_name': 'Item da Compra/ContrataÃ§Ã£o', 'verbose_name_plural': 'Itens da Compra/ContrataÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='documentorevisao',
            options={'ordering': ['-versao'], 'verbose_name': 'RevisÃ£o de Documento', 'verbose_name_plural': 'RevisÃµes de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ['-data_medicao'], 'verbose_name': 'MediÃ§Ã£o', 'verbose_name_plural': 'MediÃ§Ãµes'},
        ),
        migrations.AlterModelOptions(
            name='medicaoitem',
            options={'verbose_name': 'Item da MediÃ§Ã£o', 'verbose_name_plural': 'Itens da MediÃ§Ã£o'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de UsuÃ¡rio', 'verbose_name_plural': 'Perfis de UsuÃ¡rio'},
        ),
        migrations.AlterModelOptions(
            name='usuarioempresa',
            options={'verbose_name': 'UsuÃ¡rio de Empresa', 'verbose_name_plural': 'UsuÃ¡rios de Empresa'},
        ),
        migrations.AlterField(
            model_name='aditivocontrato',
            name='descricao',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='alertaoperacional',
            name='descricao',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='anexooperacional',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'CriaÃ§Ã£o'), ('UPDATE', 'AtualizaÃ§Ã£o'), ('DELETE', 'ExclusÃ£o'), ('APPROVE', 'AprovaÃ§Ã£o'), ('REJECT', 'RejeiÃ§Ã£o'), ('UPLOAD', 'Upload de arquivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('CONTRATO', 'Contrato (ServiÃ§o)'), ('PEDIDO_COMPRA', 'Pedido de Compra (Material)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='codigo_documento',
            field=models.CharField(help_text='CÃ³digo Ãºnico do documento', max_length=30),
        ),
        migrations.AlterField(
            model_name='documento',
            name='plano_contas',
            field=models.ForeignKey(blank=True, help_text='Vincular Ã\xa0 EAP nÃ\xadvel 5', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='Construtask.planocontas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em RevisÃ£o'), ('APROVADO', 'Aprovado'), ('OBSOLETO', 'Obsoleto')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('PROCEDIMENTO', 'Procedimento'), ('INSTRUCAO', 'InstruÃ§Ã£o de Trabalho'), ('REGISTRO', 'Registro de Qualidade'), ('MANUAL', 'Manual'), ('POLITICA', 'PolÃ\xadtica'), ('ROTEIRO', 'Roteiro/Checklist'), ('FORMULARIO', 'FormulÃ¡rio'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='arquivo_aprovado',
            field=models.FileField(blank=True, help_text='CÃ³pia imutÃ¡vel do arquivo aprovado', upload_to='documentos/aprovados/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='parecer',
            field=models.TextField(blank=True, help_text='Parecer sobre a revisÃ£o'),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='status',
            field=models.CharField(choices=[('ELABORACAO', 'Em ElaboraÃ§Ã£o'), ('REVISAO', 'Em RevisÃ£o'), ('APROVADO', 'Aprovado')], default='ELABORACAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicooperacional',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='jobassincrono',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='tipo',
            field=models.CharField(choices=[('SERVICO', 'Nota de ServiÃ§o'), ('MATERIAL', 'Nota de Material')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamentobaseline',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='orcamentobaselineitem',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='planocontas',
            name='descricao',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='is_admin_empresa',
            field=models.BooleanField(default=False, help_text='Se marcado, este usuÃ¡rio pode gerenciar usuÃ¡rios e liberar obras da empresa.'),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='obras_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Obras que este usuÃ¡rio pode acessar. Se vazio e nÃ£o for admin, nÃ£o terÃ¡ acesso a nenhuma obra.', related_name='usuarios_permitidos', to='Construtask.obra'),
        ),
    ]
