# Generated by Django 6.0.2 on 2026-04-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0051_alter_compromisso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('APPROVE', 'Aprovação'), ('REJECT', 'Rejeição'), ('UPLOAD', 'Upload de arquivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='entidade_label',
            field=models.CharField(max_length=900),
        ),
    ]
