# Generated by Django 6.0.2 on 2026-04-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0052_alter_auditevent_acao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ['-data_medicao'], 'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('CONTRATO', 'Contrato (Serviço)'), ('PEDIDO_COMPRA', 'Pedido de Compra (Material)')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlanoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20, verbose_name='Plano')),
                ('max_usuarios', models.PositiveIntegerField(blank=True, help_text='Máximo de usuários ativos. Nulo = ilimitado (Enterprise).', null=True)),
                ('max_obras', models.PositiveIntegerField(blank=True, help_text='Máximo de obras ativas. Nulo = ilimitado (Enterprise).', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='Construtask.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Plano da Empresa',
                'verbose_name_plural': 'Planos das Empresas',
            },
        ),
    ]
