# Generated by Django 6.0.4 on 2026-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0053_alter_medicao_options_alter_compromisso_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaoitem',
            options={'verbose_name': 'Item da Medição', 'verbose_name_plural': 'Itens da Medição'},
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovacao'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('PROCEDIMENTO', 'Procedimento'), ('INSTRUCAO', 'Instrução de Trabalho'), ('REGISTRO', 'Registro de Qualidade'), ('MANUAL', 'Manual'), ('POLITICA', 'Política'), ('ROTEIRO', 'Roteiro/Checklist'), ('FORMULARIO', 'Formulário'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
