# Generated by Django 5.2.13 on 2026-04-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0054_alter_medicaoitem_options_alter_cotacao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naoconformidade',
            name='evidencia_encerramento_anexo',
            field=models.FileField(blank=True, null=True, upload_to='qualidade/nao_conformidades/encerramento/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='evidencia_tratamento_anexo',
            field=models.FileField(blank=True, null=True, upload_to='qualidade/nao_conformidades/tratamento/%Y/%m/'),
        ),
    ]
