# Generated by Django 5.2.13 on 2026-04-24 12:41

import Construtask.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0055_naoconformidade_evidencia_encerramento_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexooperacional',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=Construtask.upload_paths.upload_anexo_operacional),
        ),
        migrations.AlterField(
            model_name='cotacaoanexo',
            name='arquivo',
            field=models.FileField(upload_to=Construtask.upload_paths.upload_cotacao_anexo),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='arquivo',
            field=models.FileField(help_text='Arquivo do documento (PDF, DOCX)', upload_to=Construtask.upload_paths.upload_documento_revisao),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='arquivo_aprovado',
            field=models.FileField(blank=True, help_text='CÃ³pia imutÃ¡vel do arquivo aprovado', upload_to=Construtask.upload_paths.upload_documento_aprovado),
        ),
        migrations.AlterField(
            model_name='jobassincrono',
            name='arquivo_entrada',
            field=models.FileField(blank=True, null=True, upload_to=Construtask.upload_paths.upload_job_entrada),
        ),
        migrations.AlterField(
            model_name='jobassincrono',
            name='arquivo_resultado',
            field=models.FileField(blank=True, null=True, upload_to=Construtask.upload_paths.upload_job_resultado),
        ),
        migrations.AlterField(
            model_name='naoconformidade',
            name='evidencia_encerramento_anexo',
            field=models.FileField(blank=True, null=True, upload_to=Construtask.upload_paths.upload_nao_conformidade_encerramento),
        ),
        migrations.AlterField(
            model_name='naoconformidade',
            name='evidencia_tratamento_anexo',
            field=models.FileField(blank=True, null=True, upload_to=Construtask.upload_paths.upload_nao_conformidade_tratamento),
        ),
        migrations.AlterField(
            model_name='planofisico',
            name='arquivo_origem',
            field=models.FileField(blank=True, help_text='Arquivo original importado (MPP/XLSX)', null=True, upload_to=Construtask.upload_paths.upload_cronograma_origem),
        ),
        migrations.AlterField(
            model_name='planofisicobaseline',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=Construtask.upload_paths.upload_cronograma_baseline),
        ),
    ]
