# Generated by Django 5.2.13 on 2026-05-05 16:04

import Construtask.upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0056_alter_anexooperacional_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertaoperacionalhistorico',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Histórico de Alerta Operacional', 'verbose_name_plural': 'Historicos de Alertas Operacionais'},
        ),
        migrations.AlterModelOptions(
            name='compromisso',
            options={'verbose_name': 'Compras e Contratações', 'verbose_name_plural': 'Compras e Contratações'},
        ),
        migrations.AlterModelOptions(
            name='compromissoitem',
            options={'verbose_name': 'Item da Compra/Contratação', 'verbose_name_plural': 'Itens da Compra/Contratação'},
        ),
        migrations.AlterModelOptions(
            name='cotacao',
            options={'ordering': ['-data_cotacao', '-id'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterModelOptions(
            name='cotacaoanexo',
            options={'ordering': ['id'], 'verbose_name': 'Anexo da Cotação', 'verbose_name_plural': 'Anexos das Cotações'},
        ),
        migrations.AlterModelOptions(
            name='documentorevisao',
            options={'ordering': ['-versao'], 'verbose_name': 'Revisão de Documento', 'verbose_name_plural': 'Revisões de Documentos'},
        ),
        migrations.AlterModelOptions(
            name='execucaoregraoperacional',
            options={'ordering': ['-executado_em'], 'verbose_name': 'Execução de Regra Operacional', 'verbose_name_plural': 'Execucoes de Regras Operacionais'},
        ),
        migrations.AlterModelOptions(
            name='fornecedoravaliacao',
            options={'ordering': ['-avaliado_em'], 'verbose_name': 'Avaliação de Fornecedor', 'verbose_name_plural': 'Avaliações de Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='historicooperacional',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Histórico Operacional', 'verbose_name_plural': 'Historicos Operacionais'},
        ),
        migrations.AlterModelOptions(
            name='historicoreuniaocomunicacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Histórico de Reunião de Comunicacao', 'verbose_name_plural': 'Historicos de Reunioes de Comunicacao'},
        ),
        migrations.AlterModelOptions(
            name='mapacorrespondencia',
            options={'ordering': ['plano_fisico_item'], 'verbose_name': 'Mapeamento Cronograma ↔ Orçamento', 'verbose_name_plural': 'Mapeamentos Cronograma ↔ Orçamento'},
        ),
        migrations.AlterModelOptions(
            name='metricarequisicao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Métrica de Requisição', 'verbose_name_plural': 'Métricas de Requisição'},
        ),
        migrations.AlterModelOptions(
            name='operacaobackupsaas',
            options={'ordering': ['-executado_em'], 'verbose_name': 'Operação de Backup SaaS', 'verbose_name_plural': 'Operacoes de Backup SaaS'},
        ),
        migrations.AlterModelOptions(
            name='orcamentobaseline',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Baseline de Orçamento', 'verbose_name_plural': 'Baselines de Orçamento'},
        ),
        migrations.AlterModelOptions(
            name='orcamentobaselineitem',
            options={'ordering': ['codigo'], 'verbose_name': 'Item da Baseline de Orçamento', 'verbose_name_plural': 'Itens da Baseline de Orçamento'},
        ),
        migrations.AlterModelOptions(
            name='parametroalertaempresa',
            options={'verbose_name': 'Parametro de Alerta da Empresa', 'verbose_name_plural': 'Parâmetros de Alertas da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='parametrocomunicacaoempresa',
            options={'verbose_name': 'Parametro de Comunicacao da Empresa', 'verbose_name_plural': 'Parâmetros de Comunicacao da Empresa'},
        ),
        migrations.AlterModelOptions(
            name='permissaomoduloacao',
            options={'ordering': ['modulo', 'acao'], 'verbose_name': 'Permissão por Módulo', 'verbose_name_plural': 'Permissões por Módulo'},
        ),
        migrations.AlterModelOptions(
            name='planofisico',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cronograma Físico', 'verbose_name_plural': 'Cronogramas Fisicos'},
        ),
        migrations.AlterModelOptions(
            name='reuniaocomunicacao',
            options={'ordering': ['-data_prevista', '-criado_em'], 'verbose_name': 'Reunião de Comunicacao', 'verbose_name_plural': 'Reunioes de Comunicacao'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaocompra',
            options={'ordering': ['-data_solicitacao', '-id'], 'verbose_name': 'Solicitação de Compra', 'verbose_name_plural': 'Solicitações de Compra'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AlterModelOptions(
            name='usuarioempresa',
            options={'verbose_name': 'Usuário de Empresa', 'verbose_name_plural': 'Usuários de Empresa'},
        ),
        migrations.AlterField(
            model_name='aditivocontrato',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertaoperacionalhistorico',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('TRATAMENTO', 'Em Tratamento'), ('JUSTIFICATIVA', 'Justificativa'), ('ENCERRAMENTO', 'Encerramento'), ('REABERTURA', 'Reabertura')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execução'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='consentimentolgpd',
            name='categoria_titular',
            field=models.CharField(choices=[('USUARIO', 'Usuário'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('TERCEIRO', 'Terceiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='codigo_documento',
            field=models.CharField(help_text='Código único do documento', max_length=30),
        ),
        migrations.AlterField(
            model_name='documento',
            name='plano_contas',
            field=models.ForeignKey(blank=True, help_text='Vincular Ã\xa0 EAP nível 5', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='Construtask.planocontas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado'), ('OBSOLETO', 'Obsoleto')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='arquivo_aprovado',
            field=models.FileField(blank=True, help_text='Cópia imutável do arquivo aprovado', upload_to=Construtask.upload_paths.upload_documento_aprovado),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='parecer',
            field=models.TextField(blank=True, help_text='Parecer sobre a revisão'),
        ),
        migrations.AlterField(
            model_name='documentorevisao',
            name='status',
            field=models.CharField(choices=[('ELABORACAO', 'Em Elaboração'), ('REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado')], default='ELABORACAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicoreuniaocomunicacao',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('PAUTA_VALIDADA', 'Pauta Validada'), ('PAUTA_ATUALIZADA', 'Pauta Atualizada'), ('ENVIO_APROVACAO', 'Envio para Aprovação'), ('APROVACAO', 'Aprovação'), ('AJUSTE', 'Retorno para Ajuste')], max_length=30),
        ),
        migrations.AlterField(
            model_name='itempautareuniao',
            name='categoria',
            field=models.CharField(choices=[('ALERTA', 'Alerta'), ('RISCO', 'Risco'), ('NAO_CONFORMIDADE', 'Não Conformidade'), ('CRONOGRAMA', 'Cronograma'), ('CONTRATO', 'Contrato'), ('MEDICAO', 'Medição'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='itempautareuniao',
            name='origem_tipo',
            field=models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual')], default='AUTOMATICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobassincrono',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobassincrono',
            name='tipo',
            field=models.CharField(choices=[('SINCRONIZAR_ALERTAS_OBRA', 'Sincronizar alertas da obra'), ('IMPORTAR_PLANO_CONTAS', 'Importar plano de contas'), ('GERAR_RELATORIO_FINANCEIRO', 'Gerar relatório financeiro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='status',
            field=models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('EM_APROVACAO', 'Em Aprovação'), ('CONFERIDA', 'Conferida'), ('APROVADA', 'Aprovada'), ('FATURADA', 'Faturada')], default='EM_ELABORACAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='tipo',
            field=models.CharField(choices=[('SERVICO', 'Nota de Serviço'), ('MATERIAL', 'Nota de Material')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operacaobackupsaas',
            name='tipo',
            field=models.CharField(choices=[('BACKUP', 'Backup'), ('TESTE_RESTAURACAO', 'Teste de recuperação')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orcamentobaseline',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADA', 'Aprovada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADA', 'Aprovada'), ('PARCIAL', 'Parcial'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='planofisico',
            name='baseline_de',
            field=models.ForeignKey(blank=True, help_text='Qual baseline originou esta versão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines', to='Construtask.planofisico'),
        ),
        migrations.AlterField(
            model_name='planofisico',
            name='titulo',
            field=models.CharField(help_text='Título do cronograma', max_length=200),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='codigo_atividade',
            field=models.CharField(help_text='Código da atividade (do arquivo)', max_length=50),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='codigo_eap_importado',
            field=models.CharField(blank=True, help_text='Código da EAP informado no arquivo importado', max_length=100),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='erro_vinculo_eap',
            field=models.CharField(blank=True, help_text='Erro de vinculo quando o código da EAP não existir', max_length=255),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='predecessor',
            field=models.CharField(blank=True, help_text='Código da predecessora', max_length=50),
        ),
        migrations.AlterField(
            model_name='planofisicoitem',
            name='successor',
            field=models.CharField(blank=True, help_text='Código da sucessora', max_length=50),
        ),
        migrations.AlterField(
            model_name='registroacessodadopessoal',
            name='categoria_titular',
            field=models.CharField(choices=[('USUARIO', 'Usuário'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('TERCEIRO', 'Terceiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrotratamentodadopessoal',
            name='acao',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('ANONIMIZACAO', 'Anonimização'), ('EXCLUSAO_LOGICA', 'Exclusão logica'), ('DESCARTE', 'Descarte'), ('CONSENTIMENTO', 'Consentimento'), ('REVOGACAO_CONSENTIMENTO', 'Revogacao de consentimento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='registrotratamentodadopessoal',
            name='categoria_titular',
            field=models.CharField(choices=[('USUARIO', 'Usuário'), ('COLABORADOR', 'Colaborador'), ('FORNECEDOR', 'Fornecedor'), ('CLIENTE', 'Cliente'), ('TERCEIRO', 'Terceiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reuniaocomunicacao',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PAUTA_VALIDADA', 'Pauta Validada'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADA', 'Aprovada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reuniaocomunicacao',
            name='tipo_reuniao',
            field=models.CharField(choices=[('CURTO_PRAZO', 'Curto Prazo'), ('MEDIO_PRAZO', 'Médio Prazo'), ('LONGO_PRAZO', 'Longo Prazo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaocompra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADA', 'Aprovada'), ('COTANDO', 'Em Cotação'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='is_admin_empresa',
            field=models.BooleanField(default=False, help_text='Se marcado, este usuário pode gerenciar usuários e liberar obras da empresa.'),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='obras_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Obras que este usuário pode acessar. Se vazio e não for admin, não terá acesso a nenhuma obra.', related_name='usuarios_permitidos', to='Construtask.obra'),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='papel_aprovacao',
            field=models.CharField(choices=[('GERENTE_OBRAS', 'Gerente de Obras'), ('COORDENADOR_OBRAS', 'Coordenador de Obras'), ('ENGENHEIRO_OBRAS', 'Engenheiro de Obras'), ('TECNICO_OBRAS', 'Técnico de Obras')], default='TECNICO_OBRAS', help_text='Define a alçada de aprovação operacional do usuário.', max_length=30),
        ),
    ]
