# Generated by Django 5.2.13 on 2026-05-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construtask', '0059_alter_planofisicoitem_percentual_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromissos', to='Construtask.fornecedor'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes', to='Construtask.fornecedor'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='fornecedor_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='Construtask.fornecedor'),
        ),
    ]
