"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured


def _env_bool(name, default=False):
    return (os.environ.get(name, str(default)) or str(default)).lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


def _env_json(name, default=None):
    raw_value = os.environ.get(name, "")
    if not raw_value:
        return {} if default is None else default
    try:
        return json.loads(raw_value)
    except json.JSONDecodeError as exc:
        raise ImproperlyConfigured(f"Valor invalido em {name}: JSON esperado.") from exc


def _redis_db_url(base_url, db_index):
    base = (base_url or "redis://localhost:6379").rstrip("/")
    if base.rsplit("/", 1)[-1].isdigit():
        base = base.rsplit("/", 1)[0]
    return f"{base}/{db_index}"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.environ.get("DJANGO_DEBUG")
# Local (sem DATABASE_URL): default DEBUG=True. Produção/railway: siga DJANGO_DEBUG (ou False).
if _debug_env is None and not os.environ.get("DATABASE_URL"):
    DEBUG = True
else:
    DEBUG = (_debug_env or "False").lower() in {"1", "true", "yes", "on"}

if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    SECRET_KEY = "django-insecure-development-key"
else:
    raise ImproperlyConfigured(
        "Defina DJANGO_SECRET_KEY ou SECRET_KEY em ambiente nao local."
    )

CONSTRUTASK_ENVIRONMENT = os.environ.get("CONSTRUTASK_ENVIRONMENT", "development" if DEBUG else "production").lower()
CONSTRUTASK_ADMIN_SUPERUSER_USERNAME = os.environ.get("CONSTRUTASK_ADMIN_SUPERUSER_USERNAME", "Construtask")
CONSTRUTASK_ADMIN_URL = f"{(os.environ.get('CONSTRUTASK_ADMIN_URL', 'admin/') or 'admin/').strip().strip('/') or 'admin'}/"
CONSTRUTASK_REQUIRE_EXPLICIT_HOSTS_IN_PRODUCTION = _env_bool("CONSTRUTASK_REQUIRE_EXPLICIT_HOSTS_IN_PRODUCTION", not DEBUG)
ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Construtask',
    "mptt",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'Construtask.observability.RequestObservabilityMiddleware',
    'Construtask.sentry_middleware.SentryContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Construtask.audit.AuditMiddleware',
    'Construtask.auth_middleware.LoginRequiredMiddleware',
]


ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Construtask.context_processors.obra_contexto',
                'Construtask.context_processors.user_permissoes',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'

if os.environ.get("DATABASE_URL"):
    # Ambiente Railway / Produção
    DATABASES = {
        "default": dj_database_url.parse(
            os.environ.get("DATABASE_URL"),
            conn_max_age=600,
            conn_health_checks=False,
        )
    }
else:
    # Ambiente local (SQLite)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True
USE_L10N = True
USE_TZ = True

USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_STORAGE_BACKEND = os.environ.get("DJANGO_MEDIA_STORAGE_BACKEND", "django.core.files.storage.FileSystemStorage")
MEDIA_STORAGE_OPTIONS = _env_json("DJANGO_MEDIA_STORAGE_OPTIONS_JSON", {})
CONSTRUTASK_MEDIA_PERSISTENT = _env_bool(
    "CONSTRUTASK_MEDIA_PERSISTENT",
    DEBUG or MEDIA_STORAGE_BACKEND != "django.core.files.storage.FileSystemStorage",
)
CONSTRUTASK_FILESYSTEM_MEDIA_ALLOWED_IN_PRODUCTION = _env_bool("CONSTRUTASK_FILESYSTEM_MEDIA_ALLOWED_IN_PRODUCTION", DEBUG)
CONSTRUTASK_BACKUP_ENABLED = _env_bool("CONSTRUTASK_BACKUP_ENABLED", DEBUG)
CONSTRUTASK_BACKUP_PROVIDER = os.environ.get("CONSTRUTASK_BACKUP_PROVIDER", "filesystem-local" if DEBUG else "")
CONSTRUTASK_BACKUP_RETENTION_DAYS = int(os.environ.get("CONSTRUTASK_BACKUP_RETENTION_DAYS", "7" if DEBUG else "30"))
CONSTRUTASK_BACKUP_INTERVAL_HOURS = int(os.environ.get("CONSTRUTASK_BACKUP_INTERVAL_HOURS", "24"))
CONSTRUTASK_BACKUP_LAST_SUCCESS_AT = os.environ.get("CONSTRUTASK_BACKUP_LAST_SUCCESS_AT", "")
CONSTRUTASK_LOGIN_MAX_ATTEMPTS = int(os.environ.get("CONSTRUTASK_LOGIN_MAX_ATTEMPTS", "5"))
CONSTRUTASK_LOGIN_LOCKOUT_MINUTES = int(os.environ.get("CONSTRUTASK_LOGIN_LOCKOUT_MINUTES", "15"))
CONSTRUTASK_LOGIN_IP_MAX_ATTEMPTS = int(os.environ.get("CONSTRUTASK_LOGIN_IP_MAX_ATTEMPTS", "10"))
CONSTRUTASK_LOGIN_IP_LOCKOUT_MINUTES = int(os.environ.get("CONSTRUTASK_LOGIN_IP_LOCKOUT_MINUTES", "15"))
CONSTRUTASK_LIST_PAGE_SIZE = int(os.environ.get("CONSTRUTASK_LIST_PAGE_SIZE", "20"))
CONSTRUTASK_METRICAS_RETENTION_DAYS = int(os.environ.get("CONSTRUTASK_METRICAS_RETENTION_DAYS", "30" if DEBUG else "90"))
CONSTRUTASK_ERROS_APLICACAO_RETENTION_DAYS = int(
    os.environ.get("CONSTRUTASK_ERROS_APLICACAO_RETENTION_DAYS", "60" if DEBUG else "180")
)
CONSTRUTASK_SLOW_REQUEST_THRESHOLD_MS = int(os.environ.get("CONSTRUTASK_SLOW_REQUEST_THRESHOLD_MS", "1000"))
CONSTRUTASK_HOME_CACHE_TTL = int(os.environ.get("CONSTRUTASK_HOME_CACHE_TTL", "120"))
CONSTRUTASK_PLANEJAMENTO_CACHE_TTL = int(os.environ.get("CONSTRUTASK_PLANEJAMENTO_CACHE_TTL", "180"))
CONSTRUTASK_ALERTAS_SYNC_TTL = int(os.environ.get("CONSTRUTASK_ALERTAS_SYNC_TTL", "120"))
CONSTRUTASK_ASYNC_ALERT_SYNC_ENABLED = _env_bool("CONSTRUTASK_ASYNC_ALERT_SYNC_ENABLED", not DEBUG)

_REDIS_BASE = os.environ.get("REDIS_URL", "redis://localhost:6379")
_cache_backend = os.environ.get("CONSTRUTASK_CACHE_BACKEND", "").strip()
if not _cache_backend:
    _cache_backend = "django_redis.cache.RedisCache" if os.environ.get("REDIS_URL") else "django.core.cache.backends.locmem.LocMemCache"
_cache_timeout = int(os.environ.get("CONSTRUTASK_CACHE_TIMEOUT", "300"))
_cache_ignore_exceptions = _env_bool("CONSTRUTASK_CACHE_IGNORE_EXCEPTIONS", DEBUG)

CACHES = {
    "critical": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "construtask-critical",
        "TIMEOUT": _cache_timeout,
    }
}

if _cache_backend == "django_redis.cache.RedisCache":
    CACHES["default"] = {
        "BACKEND": _cache_backend,
        "LOCATION": _redis_db_url(_REDIS_BASE, 1),  # DB 1 para cache
        "TIMEOUT": _cache_timeout,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": _cache_ignore_exceptions,
            "LOG_IGNORED_EXCEPTIONS": _cache_ignore_exceptions,
        },
        "KEY_PREFIX": "construtask",
    }
else:
    CACHES["default"] = {
        "BACKEND": _cache_backend,
        "LOCATION": os.environ.get("CONSTRUTASK_CACHE_LOCATION", "construtask-default"),
        "TIMEOUT": _cache_timeout,
        "KEY_PREFIX": "construtask",
    }

DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

STATICFILES_DIRS = []

STORAGES = {
    "default": {
        "BACKEND": MEDIA_STORAGE_BACKEND,
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG else "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
if MEDIA_STORAGE_BACKEND == "django.core.files.storage.FileSystemStorage":
    STORAGES["default"]["OPTIONS"] = {
        "location": str(MEDIA_ROOT),
        "base_url": MEDIA_URL,
    }
elif MEDIA_STORAGE_OPTIONS:
    STORAGES["default"]["OPTIONS"] = MEDIA_STORAGE_OPTIONS

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Auth settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'obra_list'
LOGOUT_REDIRECT_URL = 'login'


# Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 dias
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

if not DEBUG:
    if _env_bool("SECURE_PROXY_SSL_HEADER_ENABLED", True):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
        USE_X_FORWARDED_HOST = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True").lower() in {"1", "true", "yes", "on"}
    SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "True").lower() in {"1", "true", "yes", "on"}
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True").lower() in {"1", "true", "yes", "on"}


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = _redis_db_url(_REDIS_BASE, 0)
CELERY_RESULT_BACKEND = _redis_db_url(_REDIS_BASE, 0)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_SOFT_TIME_LIMIT = 300   # 5 min: lança SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT = 360        # 6 min: mata o worker se travar
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BEAT_SCHEDULE = {}

if CONSTRUTASK_BACKUP_ENABLED and CONSTRUTASK_BACKUP_PROVIDER:
    CELERY_BEAT_SCHEDULE["construtask-backup-postgres-r2"] = {
        "task": "Construtask.tasks.task_executar_backup_postgres",
        "schedule": timedelta(hours=max(CONSTRUTASK_BACKUP_INTERVAL_HOURS, 1)),
    }


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "structured",
        },
    },
    "loggers": {
        "construtask.request": {
            "handlers": ["console"],
            "level": os.environ.get("CONSTRUTASK_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "construtask.error": {
            "handlers": ["console"],
            "level": os.environ.get("CONSTRUTASK_ERROR_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },    "django_redis": {
        "handlers": ["console"],
        "level": "WARNING",
        "propagate": False,
    },
}
# ---------------------------------------------------------------------------
# Sentry — monitoramento de erros em produção
# ---------------------------------------------------------------------------
SENTRY_DSN = os.environ.get("SENTRY_DSN", "")

if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    import logging

    sentry_logging = LoggingIntegration(
        level=logging.INFO,         # captura INFO como breadcrumb
        event_level=logging.ERROR,  # envia ao Sentry só ERROR ou acima
    )

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style="url",
                middleware_spans=True,
                signals_spans=False,  # evita ruído de signals de auditoria
                cache_spans=True,
            ),
            CeleryIntegration(
                monitor_beat_tasks=False,
                propagate_traces=True,
            ),
            RedisIntegration(),
            sentry_logging,
        ],

        # Percentual de transações enviadas para análise de performance.
        # 0.05 = 5% — suficiente para identificar lentidão sem custo alto.
        # Aumente para 0.2 se quiser mais dados no início.
        traces_sample_rate=0.05,

        # Não enviar dados pessoais — importante para LGPD
        send_default_pii=False,

        # Ambiente e release — aparece no dashboard do Sentry
        environment=CONSTRUTASK_ENVIRONMENT,
        release=os.environ.get("RAILWAY_GIT_COMMIT_SHA", "unknown"),

        # Ignora erros esperados que poluem o dashboard
        ignore_errors=[
            "django.http.response.Http404",
            "django.core.exceptions.PermissionDenied",
            "django.contrib.auth.models.User.DoesNotExist",
        ],

        # Limite de eventos por segundo — proteção contra storm de erros
        max_breadcrumbs=30,
    )
